### ISSUE TITLE
怎么禁止横屏时表情大小的变化？

### ISSUE THREAD

**Issue by yangguanghei** [kirayamato1989/KYExpressionInputView#2]
怎么禁止横屏时表情大小的变化？

**Comment by kirayamato1989** [comment]
没有提供禁止的功能，不过你可以初始化的时候把横竖屏的表情大小设置为一样的。项目很久没有更新了，才看到你的issue

**Comment by kirayamato1989** [comment]
> 怎么禁止横屏时表情大小的变化？

没有提供禁止的功能，不过你可以初始化的时候把横竖屏的表情大小设置为一样的。项目很久没有更新了，才看到你的issue
